<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ProjectTemplate;
use App\Models\TemplateWorkingStep;
use App\Models\TemplateWorkingSubStep;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Inertia\Inertia;

class ProjectTemplateController extends Controller
{
    // ==================== BUNDLE MANAGEMENT ====================
    
    public function index()
    {
        $templates = ProjectTemplate::orderBy('name')->get();

        return Inertia::render('Admin/ProjectTemplates/TemplateIndex', [
            'bundles' => $templates, // Keep 'bundles' key for frontend compatibility
        ]);
    }

    public function createBundle()
    {
        return Inertia::render('Admin/ProjectTemplates/TemplateCreate');
    }

    public function storeBundle(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:project_templates,name',
        ]);

        ProjectTemplate::create($request->only('name'));

        return redirect()->route('admin.project-templates.template-bundles.index')
            ->with('success', 'Template Bundle berhasil dibuat!');
    }

    public function showBundle(ProjectTemplate $templateBundle)
    {
        // Get working steps for this project template
        $workingSteps = TemplateWorkingStep::where('project_template_id', $templateBundle->id)
            ->with(['templateWorkingSubSteps' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        // Initialize project_templates as empty array for compatibility with frontend
        $templateBundle->project_templates = [];

        return Inertia::render('Admin/ProjectTemplates/TemplateShow', [
            'bundle' => $templateBundle,
            'workingSteps' => $workingSteps,
        ]);
    }

    public function editBundle(ProjectTemplate $templateBundle)
    {
        // Get working steps for this project template
        $workingSteps = TemplateWorkingStep::where('project_template_id', $templateBundle->id)
            ->with(['templateWorkingSubSteps' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        // Initialize project_templates as empty array for compatibility with frontend
        $templateBundle->project_templates = [];

        return Inertia::render('Admin/ProjectTemplates/TemplateEdit', [
            'bundle' => $templateBundle,
            'workingSteps' => $workingSteps,
        ]);
    }

    public function updateBundle(Request $request, ProjectTemplate $templateBundle)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:project_templates,name,' . $templateBundle->id,
        ]);

        $templateBundle->update($request->only('name'));

        return redirect()->route('admin.project-templates.template-bundles.edit', $templateBundle->id)
            ->with('success', 'Template Bundle berhasil diupdate!');
    }

    public function destroyBundle(ProjectTemplate $templateBundle)
    {
        // Check if template has working steps
        if ($templateBundle->templateWorkingSteps()->exists()) {
            return redirect()->route('admin.project-templates.template-bundles.index')
                ->with('error', 'Tidak dapat menghapus template yang masih memiliki working steps!');
        }

        $templateBundle->delete();

        return redirect()->route('admin.project-templates.template-bundles.index')
            ->with('success', 'Template Bundle berhasil dihapus!');
    }

    // ==================== WORKING STEP MANAGEMENT ====================

    public function storeWorkingStep(Request $request)
    {
        try {
            // Support multiple parameter names for project template ID
            $projectTemplateId = $request->bundle_id ?? $request->project_template_id ?? $request->template_id;
            
            $request->validate([
                'name' => 'required|string|max:255',
            ]);

            // Validate project template exists
            if (!$projectTemplateId || !ProjectTemplate::find($projectTemplateId)) {
                return redirect()->back()->with('error', 'Project template ID tidak valid. Parameter: ' . json_encode($request->all()));
            }

            // Get next order number for this project template
            $nextOrder = TemplateWorkingStep::where('project_template_id', $projectTemplateId)
                ->max('order') + 1;

            // Create working step (slug will be auto-generated by Model)
            $workingStep = TemplateWorkingStep::create([
                'name' => $request->name,
                'project_template_id' => $projectTemplateId,
                'order' => $nextOrder,
            ]);

            return redirect()->back()->with('success', 'Working Step berhasil dibuat!');
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Gagal membuat working step: ' . $e->getMessage());
        }
    }

    public function updateWorkingStep(Request $request, TemplateWorkingStep $templateWorkingStep)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        // Update name (slug will be auto-updated by Model if name changed)
        $templateWorkingStep->update([
            'name' => $request->name,
        ]);

        return redirect()->back()->with('success', 'Template Working Step berhasil diupdate!');
    }

    public function destroyWorkingStep(TemplateWorkingStep $templateWorkingStep)
    {
        // Note: No related project template cleanup needed since 
        // ProjectTemplate structure has changed and only contains 'name' field
        
        // Delete all related sub steps
        $templateWorkingStep->templateWorkingSubSteps()->delete();
        
        // Delete the working step
        $templateWorkingStep->delete();

        return redirect()->back()->with('success', 'Template Working Step dan sub steps berhasil dihapus!');
    }

    // ==================== WORKING SUB STEP MANAGEMENT ====================

    public function storeWorkingSubStep(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'template_working_step_id' => 'required|exists:template_working_steps,id',
        ]);

        // Get the working step to get project_template_id
        $workingStep = TemplateWorkingStep::findOrFail($request->template_working_step_id);

        // Get next order number for this working step
        $nextOrder = TemplateWorkingSubStep::where('template_working_step_id', $request->template_working_step_id)
            ->max('order') + 1;

        // Create sub step (slug will be auto-generated by Model)
        $subStep = TemplateWorkingSubStep::create([
            'name' => $request->name,
            'template_working_step_id' => $request->template_working_step_id,
            'project_template_id' => $workingStep->project_template_id,
            'order' => $nextOrder,
        ]);

        return redirect()->back()->with('success', 'Template Working Sub Step berhasil dibuat!');
    }

    public function updateWorkingSubStep(Request $request, TemplateWorkingSubStep $templateWorkingSubStep)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'client_interact' => 'boolean',
            'multiple_files' => 'boolean',
        ]);

        $templateWorkingSubStep->update([
            'name' => $request->name,
            'client_interact' => $request->boolean('client_interact'),
            'multiple_files' => $request->boolean('multiple_files'),
        ]);

        return redirect()->back()->with('success', 'Template Working Sub Step berhasil diupdate!');
    }

    public function destroyWorkingSubStep(TemplateWorkingSubStep $templateWorkingSubStep)
    {
        // Note: No related project template cleanup needed since 
        // ProjectTemplate structure has changed and only contains 'name' field

        $templateWorkingSubStep->delete();

        return redirect()->back()->with('success', 'Template Working Sub Step berhasil dihapus!');
    }

    // ==================== REORDERING METHODS ====================

    public function reorderWorkingSteps(Request $request)
    {
        $request->validate([
            'steps' => 'required|array',
            'steps.*.id' => 'required|exists:template_working_steps,id',
            'steps.*.order' => 'required|integer|min:0',
        ]);

        foreach ($request->steps as $stepData) {
            TemplateWorkingStep::where('id', $stepData['id'])
                ->update(['order' => $stepData['order']]);
        }

        return response()->json(['message' => 'Working steps reordered successfully']);
    }

    public function reorderWorkingSubSteps(Request $request)
    {
        try {
            $request->validate([
                'sub_steps' => 'required|array',
                'sub_steps.*.id' => 'required|exists:template_working_sub_steps,id',
                'sub_steps.*.order' => 'required|integer|min:1',
                'sub_steps.*.template_working_step_id' => 'required|exists:template_working_steps,id',
            ]);

            foreach ($request->sub_steps as $subStepData) {
                TemplateWorkingSubStep::where('id', $subStepData['id'])
                    ->update([
                        'order' => $subStepData['order'],
                        'template_working_step_id' => $subStepData['template_working_step_id']
                    ]);
            }

            return response()->json([
                'success' => true,
                'message' => 'Working sub steps reordered successfully'
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error reordering substeps: ' . $e->getMessage()
            ], 500);
        }
    }

    // ==================== PROJECT TEMPLATE MANAGEMENT ====================
    
    // Note: Project templates now only contain 'name' field (template categories)
    // For actual template content, use TemplateWorkingStep and TemplateWorkingSubStep
}
