<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Project;
use App\Models\ProjectTeam;
use App\Models\User;
use App\Models\WorkingStep;
use App\Models\WorkingSubStep;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Inertia\Inertia;

class ProjectController extends Controller
{
    // ==================== BUNDLE MANAGEMENT ====================
    
    public function index()
    {
        $projects = Project::orderBy('name')->get();

        return Inertia::render('Admin/Project/Index', [
            'bundles' => $projects,
        ]);
    }

    public function createBundle()
    {
        return Inertia::render('Admin/Project/Create');
    }

    public function storeBundle(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:projects,name',
        ]);

        Project::create($request->only('name'));

        return redirect()->route('admin.projects.bundles.index')
            ->with('success', 'Project berhasil dibuat!');
    }

    public function showBundle(Project $bundle)
    {
        // Get working steps for this project
        $workingSteps = WorkingStep::where('project_id', $bundle->id)
            ->with(['workingSubSteps' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        return Inertia::render('Admin/Project/Show', [
            'bundle' => $bundle,
            'workingSteps' => $workingSteps,
        ]);
    }

    public function editBundle(Project $bundle)
    {
        // Get working steps for this project
        $workingSteps = WorkingStep::where('project_id', $bundle->id)
            ->with(['workingSubSteps' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        // Get team members
        $teamMembers = ProjectTeam::where('project_id', $bundle->id)
            ->with('user')
            ->orderBy('role')
            ->orderBy('user_name')
            ->get();

        // Get available users (company level only)
        $availableUsers = User::where('role', 'company')
            ->orderBy('name')
            ->get(['id', 'name', 'email', 'position']);

        return Inertia::render('Admin/Project/Edit', [
            'bundle' => $bundle,
            'workingSteps' => $workingSteps,
            'teamMembers' => $teamMembers,
            'availableUsers' => $availableUsers,
        ]);
    }

    public function updateBundle(Request $request, Project $bundle)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:projects,name,' . $bundle->id,
        ]);

        $bundle->update($request->only('name'));

        return redirect()->route('admin.projects.bundles.edit', $bundle->id)
            ->with('success', 'Project berhasil diupdate!');
    }

    public function destroyBundle(Project $bundle)
    {
        // Check if project has working steps
        if ($bundle->workingSteps()->exists()) {
            return redirect()->route('admin.projects.bundles.index')
                ->with('error', 'Tidak dapat menghapus project yang masih memiliki working steps!');
        }

        $bundle->delete();

        return redirect()->route('admin.projects.bundles.index')
            ->with('success', 'Project berhasil dihapus!');
    }

    // ==================== WORKING STEP MANAGEMENT ====================

    public function storeWorkingStep(Request $request)
    {
        try {
            // Support multiple parameter names for project ID
            $projectId = $request->bundle_id ?? $request->project_id;
            
            $request->validate([
                'name' => 'required|string|max:255',
            ]);

            // Validate project exists
            if (!$projectId || !Project::find($projectId)) {
                return redirect()->back()->with('error', 'Project ID tidak valid. Parameter: ' . json_encode($request->all()));
            }

            // Get next order number for this project
            $nextOrder = WorkingStep::where('project_id', $projectId)
                ->max('order') + 1;

            // Create working step (slug will be auto-generated by Model)
            $workingStep = WorkingStep::create([
                'name' => $request->name,
                'project_id' => $projectId,
                'order' => $nextOrder,
            ]);

            return redirect()->back()->with('success', 'Working Step berhasil dibuat!');
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Gagal membuat working step: ' . $e->getMessage());
        }
    }

    public function updateWorkingStep(Request $request, WorkingStep $workingStep)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        // Update name (slug will be auto-updated by Model if name changed)
        $workingStep->update([
            'name' => $request->name,
        ]);

        return redirect()->back()->with('success', 'Working Step berhasil diupdate!');
    }

    public function destroyWorkingStep(WorkingStep $workingStep)
    {
        // Delete all related sub steps
        $workingStep->workingSubSteps()->delete();
        
        // Delete the working step
        $workingStep->delete();

        return redirect()->back()->with('success', 'Working Step dan sub steps berhasil dihapus!');
    }

    // ==================== WORKING SUB STEP MANAGEMENT ====================

    public function storeWorkingSubStep(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'working_step_id' => 'required|exists:working_steps,id',
        ]);

        // Get the working step to get project_id
        $workingStep = WorkingStep::findOrFail($request->working_step_id);

        // Get next order number for this working step
        $nextOrder = WorkingSubStep::where('working_step_id', $request->working_step_id)
            ->max('order') + 1;

        // Create sub step (slug will be auto-generated by Model)
        $subStep = WorkingSubStep::create([
            'name' => $request->name,
            'working_step_id' => $request->working_step_id,
            'project_id' => $workingStep->project_id,
            'order' => $nextOrder,
        ]);

        return redirect()->back()->with('success', 'Working Sub Step berhasil dibuat!');
    }

    public function updateWorkingSubStep(Request $request, WorkingSubStep $workingSubStep)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'client_interact' => 'boolean',
            'multiple_files' => 'boolean',
        ]);

        $workingSubStep->update([
            'name' => $request->name,
            'client_interact' => $request->boolean('client_interact'),
            'multiple_files' => $request->boolean('multiple_files'),
        ]);

        return redirect()->back()->with('success', 'Working Sub Step berhasil diupdate!');
    }

    public function destroyWorkingSubStep(WorkingSubStep $workingSubStep)
    {
        $workingSubStep->delete();

        return redirect()->back()->with('success', 'Working Sub Step berhasil dihapus!');
    }

    // ==================== REORDERING METHODS ====================

    public function reorderWorkingSteps(Request $request)
    {
        $request->validate([
            'steps' => 'required|array',
            'steps.*.id' => 'required|exists:working_steps,id',
            'steps.*.order' => 'required|integer|min:0',
        ]);

        foreach ($request->steps as $stepData) {
            WorkingStep::where('id', $stepData['id'])
                ->update(['order' => $stepData['order']]);
        }

        return response()->json(['message' => 'Working steps reordered successfully']);
    }

    public function reorderWorkingSubSteps(Request $request)
    {
        try {
            $request->validate([
                'sub_steps' => 'required|array',
                'sub_steps.*.id' => 'required|exists:working_sub_steps,id',
                'sub_steps.*.order' => 'required|integer|min:1',
                'sub_steps.*.working_step_id' => 'required|exists:working_steps,id',
            ]);

            foreach ($request->sub_steps as $subStepData) {
                WorkingSubStep::where('id', $subStepData['id'])
                    ->update([
                        'order' => $subStepData['order'],
                        'working_step_id' => $subStepData['working_step_id']
                    ]);
            }

            return response()->json([
                'success' => true,
                'message' => 'Working sub steps reordered successfully'
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error reordering substeps: ' . $e->getMessage()
            ], 500);
        }
    }

    // ==================== PROJECT MANAGEMENT ====================
    
    public function updateProject(Request $request, Project $project)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        $project->update([
            'name' => $request->name,
        ]);

        return redirect()->back()->with('success', 'Project berhasil diupdate!');
    }

    // ==================== TEAM MANAGEMENT ====================
    
    public function storeTeamMember(Request $request)
    {
        $request->validate([
            'project_id' => 'required|exists:projects,id',
            'user_id' => 'required|exists:users,id',
            'role' => 'required|in:partner,manager,supervisor,team leader,member',
        ]);

        $project = Project::findOrFail($request->project_id);
        $user = User::findOrFail($request->user_id);

        // Check if user already in team
        $exists = ProjectTeam::where('project_id', $project->id)
            ->where('user_id', $user->id)
            ->exists();

        if ($exists) {
            return redirect()->back()->with('error', 'User sudah ada dalam tim project ini!');
        }

        // Get client name from project (assuming you have client relationship)
        $clientName = $project->client->name ?? 'N/A';

        ProjectTeam::create([
            'project_id' => $project->id,
            'user_id' => $user->id,
            'project_name' => $project->name,
            'project_client_name' => $clientName,
            'user_name' => $user->name,
            'user_email' => $user->email,
            'user_position' => $user->position ?? null,
            'role' => $request->role,
        ]);

        return redirect()->back()->with('success', 'Anggota tim berhasil ditambahkan!');
    }

    public function updateTeamMember(Request $request, $teamId)
    {
        $request->validate([
            'role' => 'required|in:partner,manager,supervisor,team leader,member',
        ]);

        $teamMember = ProjectTeam::findOrFail($teamId);
        $teamMember->update([
            'role' => $request->role,
        ]);

        return redirect()->back()->with('success', 'Role anggota tim berhasil diupdate!');
    }

    public function destroyTeamMember($teamId)
    {
        $teamMember = ProjectTeam::findOrFail($teamId);
        $teamMember->delete();

        return redirect()->back()->with('success', 'Anggota tim berhasil dihapus!');
    }
}
