<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ProjectTemplate;
use App\Models\TemplateWorkingStep;
use App\Models\TemplateTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Inertia\Inertia;

class ProjectTemplateController extends Controller
{
    // ==================== BUNDLE MANAGEMENT ====================
    
    public function index()
    {
        $templates = ProjectTemplate::orderBy('name')->get();

        return Inertia::render('Admin/ProjectTemplates/TemplateIndex', [
            'bundles' => $templates, // Keep 'bundles' key for frontend compatibility
        ]);
    }

    public function createBundle()
    {
        return Inertia::render('Admin/ProjectTemplates/TemplateCreate');
    }

    public function storeBundle(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:project_templates,name',
        ]);

        ProjectTemplate::create($request->only('name'));

        return redirect()->route('admin.project-templates.template-bundles.index')
            ->with('success', 'Template bundle created successfully!');
    }

    public function showBundle(ProjectTemplate $templateBundle)
    {
        // Get working steps for this project template
        $workingSteps = TemplateWorkingStep::where('project_template_id', $templateBundle->id)
            ->with(['templateTasks' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        // Initialize project_templates as empty array for compatibility with frontend
        $templateBundle->project_templates = [];

        return Inertia::render('Admin/ProjectTemplates/TemplateShow', [
            'bundle' => $templateBundle,
            'workingSteps' => $workingSteps,
        ]);
    }

    public function editBundle(ProjectTemplate $templateBundle)
    {
        // Get working steps for this project template
        $workingSteps = TemplateWorkingStep::where('project_template_id', $templateBundle->id)
            ->with(['templateTasks' => function($query) {
                $query->orderBy('order');
            }])
            ->orderBy('order')
            ->get();

        // Initialize project_templates as empty array for compatibility with frontend
        $templateBundle->project_templates = [];

        return Inertia::render('Admin/ProjectTemplates/TemplateEdit', [
            'bundle' => $templateBundle,
            'workingSteps' => $workingSteps,
        ]);
    }

    public function updateBundle(Request $request, ProjectTemplate $templateBundle)
    {
        $request->validate([
            'name' => 'required|string|max:255|unique:project_templates,name,' . $templateBundle->id,
        ]);

        $templateBundle->update($request->only('name'));

        return redirect()->route('admin.project-templates.template-bundles.edit', $templateBundle->id)
            ->with('success', 'Template bundle updated successfully!');
    }

    public function destroyBundle(ProjectTemplate $templateBundle)
    {
        // Check if template has working steps
        if ($templateBundle->templateWorkingSteps()->exists()) {
            return redirect()->route('admin.project-templates.template-bundles.index')
                ->with('error', 'Cannot delete template that still has working steps!');
        }

        $templateBundle->delete();

        return redirect()->route('admin.project-templates.template-bundles.index')
            ->with('success', 'Template bundle deleted successfully!');
    }

    // ==================== WORKING STEP MANAGEMENT ====================

    public function storeWorkingStep(Request $request)
    {
        try {
            // Support multiple parameter names for project template ID
            $projectTemplateId = $request->bundle_id ?? $request->project_template_id ?? $request->template_id;
            
            $request->validate([
                'name' => 'required|string|max:255',
            ]);

            // Validate project template exists
            if (!$projectTemplateId || !ProjectTemplate::find($projectTemplateId)) {
                return redirect()->back()->with('error', 'Invalid project template ID. Parameters: ' . json_encode($request->all()));
            }

            // Get next order number for this project template
            $nextOrder = TemplateWorkingStep::where('project_template_id', $projectTemplateId)
                ->max('order') + 1;

            // Create working step (slug will be auto-generated by Model)
            $workingStep = TemplateWorkingStep::create([
                'name' => $request->name,
                'project_template_id' => $projectTemplateId,
                'order' => $nextOrder,
            ]);

            return redirect()->back()->with('success', 'Working step created successfully!');
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Failed to create working step: ' . $e->getMessage());
        }
    }

    public function updateWorkingStep(Request $request, TemplateWorkingStep $templateWorkingStep)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        // Update name (slug will be auto-updated by Model if name changed)
        $templateWorkingStep->update([
            'name' => $request->name,
        ]);

        return redirect()->back()->with('success', 'Template working step updated successfully!');
    }

    public function destroyWorkingStep(TemplateWorkingStep $templateWorkingStep)
    {
        // Note: No related project template cleanup needed since 
        // ProjectTemplate structure has changed and only contains 'name' field
        
        // Delete all related tasks
        $templateWorkingStep->templateTasks()->delete();
        
        // Delete the working step
        $templateWorkingStep->delete();

        return redirect()->back()->with('success', 'Template working step and tasks deleted successfully!');
    }

    // ==================== TASK MANAGEMENT ====================

    public function storeTask(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'template_working_step_id' => 'required|exists:template_working_steps,id',
        ]);

        // Get the working step to get project_template_id
        $workingStep = TemplateWorkingStep::findOrFail($request->template_working_step_id);

        // Get next order number for this working step
        $nextOrder = TemplateTask::where('template_working_step_id', $request->template_working_step_id)
            ->max('order') + 1;

        // Generate unique slug
        $baseSlug = Str::slug($request->name);
        $slug = $baseSlug;
        $count = 1;
        while (TemplateTask::where('slug', $slug)->exists()) {
            $slug = $baseSlug . '-' . $count;
            $count++;
        }

        // Create task with generated slug
        $task = TemplateTask::create([
            'name' => $request->name,
            'slug' => $slug,
            'template_working_step_id' => $request->template_working_step_id,
            'project_template_id' => $workingStep->project_template_id,
            'order' => $nextOrder,
        ]);

        return redirect()->back()->with('success', 'Template task created successfully!');
    }

    public function updateTask(Request $request, TemplateTask $templateTask)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'client_interact' => 'boolean',
            'multiple_files' => 'boolean',
        ]);

        // Generate new slug if name changed
        $updateData = [
            'name' => $request->name,
            'client_interact' => $request->boolean('client_interact'),
            'multiple_files' => $request->boolean('multiple_files'),
        ];

        if ($templateTask->name !== $request->name) {
            $baseSlug = Str::slug($request->name);
            $slug = $baseSlug;
            $count = 1;
            while (TemplateTask::where('slug', $slug)->where('id', '!=', $templateTask->id)->exists()) {
                $slug = $baseSlug . '-' . $count;
                $count++;
            }
            $updateData['slug'] = $slug;
        }

        $templateTask->update($updateData);

        return redirect()->back()->with('success', 'Template task updated successfully!');
    }

    public function destroyTask(TemplateTask $templateTask)
    {
        // Note: No related project template cleanup needed since 
        // ProjectTemplate structure has changed and only contains 'name' field

        $templateTask->delete();

        return redirect()->back()->with('success', 'Template task deleted successfully!');
    }

    // ==================== REORDERING METHODS ====================

    public function reorderWorkingSteps(Request $request)
    {
        $request->validate([
            'steps' => 'required|array',
            'steps.*.id' => 'required|exists:template_working_steps,id',
            'steps.*.order' => 'required|integer|min:0',
        ]);

        foreach ($request->steps as $stepData) {
            TemplateWorkingStep::where('id', $stepData['id'])
                ->update(['order' => $stepData['order']]);
        }

        return response()->json(['message' => 'Working steps reordered successfully']);
    }

    public function reorderTasks(Request $request)
    {
        try {
            $request->validate([
                'tasks' => 'required|array',
                'tasks.*.id' => 'required|exists:template_tasks,id',
                'tasks.*.order' => 'required|integer|min:1',
                'tasks.*.template_working_step_id' => 'required|exists:template_working_steps,id',
            ]);

            foreach ($request->tasks as $taskData) {
                TemplateTask::where('id', $taskData['id'])
                    ->update([
                        'order' => $taskData['order'],
                        'template_working_step_id' => $taskData['template_working_step_id']
                    ]);
            }

            return response()->json([
                'success' => true,
                'message' => 'Tasks reordered successfully'
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error reordering tasks: ' . $e->getMessage()
            ], 500);
        }
    }

    // ==================== PROJECT TEMPLATE MANAGEMENT ====================
    
    // Note: Project templates now only contain 'name' field (template categories)
    // For actual template content, use TemplateWorkingStep and TemplateTask
}
